# Utilisez une image PHP comme base
FROM php:7.4-apache

# Copiez les fichiers PHP et CSS de votre application dans le conteneur
COPY index.php .
COPY style.css .

# Exposez le port 80 pour accéder à l'application web via un navigateur
EXPOSE 80
