version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mariadb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - ./liste.sql:/docker-entrypoint-initdb.d/MariaDB/liste.sql

  web:
    build:
      context: ./app
    ports:
      - "9090:90"
    depends_on:
      - db
